[package]
name = "loady"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.4"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4"
]